Repository cowaine/is-my-code-that-strange, pull requests merged in 2024-06, with the labels that each got.

#11 Feature/irisation23
  irisation23/readme/irisation23-README.md
  irisation23/src/main/java/com/cowaine/first/one/Class001.java
  irisation23/src/main/java/com/cowaine/first/one/TechnologyCentricNaming.java
  irisation23/src/main/java/com/cowaine/first/three/ContractAmount.java
  irisation23/src/main/java/com/cowaine/first/three/ContractManager.java
  irisation23/src/main/java/com/cowaine/first/three/DevilDataClass.java
  irisation23/src/main/java/com/cowaine/first/two/TooManyIfState.java
  irisation23/src/main/java/com/cowaine/first/two/domain/Magic.java
  irisation23/src/main/java/com/cowaine/first/two/domain/Member.java
  irisation23/src/main/java/com/cowaine/second/four/CloselyRelationDataAndLogic.java
  irisation23/src/main/java/com/cowaine/second/one/ExactlySendNameArchitecture.java
  irisation23/src/main/java/com/cowaine/third/two/GrowingMatureClass.java
Labels: chapter01, chapter02, chapter03

#10 chapter 1, 2, 3
  sunset0/src/main/java/com/cowaine/sunset0/Main.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter1/Class001.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter1/ContractAmount.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter1/ContractManager.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter1/MemoryStateManager.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter1/RpgGame.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter2/AttackService.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter2/HitPoint.java
  sunset0/src/main/java/com/cowaine/sunset0/chpater3/Currency.java
  sunset0/src/main/java/com/cowaine/sunset0/chpater3/Money.java
Labels: chapter01, chapter02, chapter03

#15 [1st Weeks] 1~3장 학습내용
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/Condition.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/Money.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/Naming.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/anti_pattern/TrashObject.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Money.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Naming.java
  firewoody237/src/main/java/com/cowaine/firewoody237/studyMemo.md
Labels: chapter01, chapter02, chapter03

#17 Feature/corock
  corock/build.gradle
  corock/src/main/java/com/cowaine/corock/Book.java
  corock/src/main/java/com/cowaine/corock/Main.java
  corock/src/main/java/com/cowaine/corock/chapter01/Class001.java
  corock/src/main/java/com/cowaine/corock/chapter01/MemoryStateManager.java
  corock/src/main/java/com/cowaine/corock/chapter01/contract/ContractAmount.java
  corock/src/main/java/com/cowaine/corock/chapter01/contract/ContractManager.java
  corock/src/main/java/com/cowaine/corock/chapter01/etc/EtcManager.java
  corock/src/main/java/com/cowaine/corock/chapter01/game/HitPoint.java
  corock/src/main/java/com/cowaine/corock/chapter01/game/Magic.java
  corock/src/main/java/com/cowaine/corock/chapter01/game/Member.java
  corock/src/main/java/com/cowaine/corock/chapter01/game/RpgService.java
  corock/src/main/java/com/cowaine/corock/chapter01/messaging/MessageManager.java
  corock/src/main/java/com/cowaine/corock/chapter01/screening/ScreeningManager.java
  corock/src/main/java/com/cowaine/corock/chapter02/game/Damage.java
Labels: chapter01, chapter02, chapter03

#20 Feature/coalong
  coalong/src/main/java/com/cowaine/coalong/Main.java
  coalong/src/main/java/com/cowaine/coalong/README.md
  coalong/src/main/java/com/cowaine/coalong/chapter01/badnaming/Class001.java
  coalong/src/main/java/com/cowaine/coalong/chapter01/badnaming/MemoryStateManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter01/contract/AntiPattern.java
  coalong/src/main/java/com/cowaine/coalong/chapter01/contract/ContractAmount.java
  coalong/src/main/java/com/cowaine/coalong/chapter01/contract/ContractManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter01/rpggame/Magic.java
  coalong/src/main/java/com/cowaine/coalong/chapter01/rpggame/Member.java
  coalong/src/main/java/com/cowaine/coalong/chapter01/rpggame/RpgPlay.java
  coalong/src/main/java/com/cowaine/coalong/chapter02/Damage.java
  coalong/src/main/java/com/cowaine/coalong/chapter02/HitPoint.java
  coalong/src/main/java/com/cowaine/coalong/chapter03/Money.java
Labels: chapter01, chapter02, chapter03

#24 [2st Weeks] 4~5장 학습내용
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/ActorManager.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/Common.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/Coupling.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/GiftPoint.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/NoDemeter.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/ReAssign.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/ToManyParameters.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/GiftPoint.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Immutable.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Location.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/MagicPoint.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/NotManyParameters.java
  firewoody237/src/main/java/com/cowaine/firewoody237/studyMemo.md
Labels: chapter04, chapter05

#29 Feature/irisation23
  irisation23/readme/irisation23-README.md
  irisation23/src/main/java/com/cowaine/fifth/one/MisuseStatic.java
  irisation23/src/main/java/com/cowaine/fifth/two/SeperateInitializeLogic.java
  irisation23/src/main/java/com/cowaine/fourth/one/Reallocation.java
  irisation23/src/main/java/com/cowaine/fourth/two/UnintendedImpactsDueToVariability.java
Labels: chapter04, chapter05

#33 Feature/0sunset0
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/reassignment/Damage.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/reassignment/Order.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/use_immutability_variability/HitPoint.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/use_immutability_variability/StateType.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/use_immutability_variability/States.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/variability_effects/AttackPower.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/variability_effects/AttackPowerV2.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/variability_effects/Weapon.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter4/variability_effects/WeaponV2.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/ActorManager.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/Common.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/ConsumptionPoint.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/Equipments.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/Game.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/GiftPoint.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/GiftPointFactory.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/Location.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/OrderManager.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter5/PaymentManager.java
  sunset0/src/main/java/com/cowaine/sunset0/chpater3/Currency.java
  sunset0/src/main/java/com/cowaine/sunset0/chpater3/Money.java
Labels: chapter04, chapter05

#35 Feature/snoopingh
  snoopingh/src/main/java/com/cowaine/snoopingh/chap03/Money.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap04/AttackPower.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap04/HitPoint.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap04/Main.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap04/Weapon.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap05/DiscountRate.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap05/DiscountedPrice.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap05/GiftPoint.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap05/GiftPointFactory.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap05/MagicPoint.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap05/RegularPrice.java
Labels: chapter04, chapter05

#37 Feature/corock
  corock/src/main/java/com/cowaine/corock/chapter01/Book.java
  corock/src/main/java/com/cowaine/corock/chapter02/Book.java
  corock/src/main/java/com/cowaine/corock/chapter02/game/Damage.java
  corock/src/main/java/com/cowaine/corock/chapter02/game/Game.java
  corock/src/main/java/com/cowaine/corock/chapter02/game/HitPoint.java
  corock/src/main/java/com/cowaine/corock/chapter03/Book.java
  corock/src/main/java/com/cowaine/corock/chapter03/domain/Money.java
  corock/src/main/java/com/cowaine/corock/chapter04/Book.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/AttackPower.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/Damage.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/Enemy.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/HitPoint.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/Member.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/StateType.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/States.java
  corock/src/main/java/com/cowaine/corock/chapter04/game/Weapon.java
  corock/src/main/java/com/cowaine/corock/chapter04/product/Product.java
  corock/src/main/java/com/cowaine/corock/chapter05/Book.java
  corock/src/main/java/com/cowaine/corock/chapter05/auth/User.java
  corock/src/main/java/com/cowaine/corock/chapter05/cart/Cart.java
  corock/src/main/java/com/cowaine/corock/chapter05/cart/CartService.java
  corock/src/main/java/com/cowaine/corock/chapter05/cart/DefaultCartService.java
  corock/src/main/java/com/cowaine/corock/chapter05/common/Common.java
  corock/src/main/java/com/cowaine/corock/chapter05/domain/DiscountManager.java
  corock/src/main/java/com/cowaine/corock/chapter05/domain/DiscountRate.java
  corock/src/main/java/com/cowaine/corock/chapter05/domain/DiscountedPrice.java
  corock/src/main/java/com/cowaine/corock/chapter05/domain/MoneyData.java
  corock/src/main/java/com/cowaine/corock/chapter05/domain/RegularPrice.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/ActorManager.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/Armor.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/Equipment.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/Equipments.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/Game.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/Location.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/MagicPoint.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/Member.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/Party.java
  corock/src/main/java/com/cowaine/corock/chapter05/game/SpecialAttackManager.java
  corock/src/main/java/com/cowaine/corock/chapter05/order/Money.java
  corock/src/main/java/com/cowaine/corock/chapter05/order/OrderManager.java
  corock/src/main/java/com/cowaine/corock/chapter05/payment/PaymentManager.java
  corock/src/main/java/com/cowaine/corock/chapter05/point/ConsumptionPoint.java
  corock/src/main/java/com/cowaine/corock/chapter05/point/GiftPoint.java
  corock/src/main/java/com/cowaine/corock/chapter05/product/AmountIncludingTax.java
  corock/src/main/java/com/cowaine/corock/chapter05/product/Product.java
  corock/src/main/java/com/cowaine/corock/chapter05/product/TaxRate.java
  corock/src/main/java/com/cowaine/corock/chapter05/util/Logger.java
  corock/src/main/java/com/cowaine/corock/chapter05/util/MagicPointUtils.java
  corock/src/main/java/com/cowaine/corock/chapter05/util/Utils.java
Labels: chapter04, chapter05

#38 Feature/coalong
  coalong/src/main/java/com/cowaine/coalong/Main.java
  coalong/src/main/java/com/cowaine/coalong/chapter03/Money.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex01/Damage.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex01/Enemy.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex01/Member.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex02/AttackGame.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex02/AttackPower.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex02/Weapon.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex03/HitPoint.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex03/Member.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex03/StateType.java
  coalong/src/main/java/com/cowaine/coalong/chapter04/ex03/States.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/ActorManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/AmountIncludingTax.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/Common.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/ConsumptionPoint.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/DiscountManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/DiscountRate.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/DiscountedPrice.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/GiftPoint.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/Location.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/MagicPoint.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/Main05.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/MoneyData.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/OrderManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/PaymentManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/Product.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/RegularPrice.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/SpecialAttackManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/TaxRate.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/User.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/Util.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/game/Armor.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/game/Equipment.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/game/Equipments.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/game/Member.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/game/Party.java
  coalong/src/main/java/com/cowaine/coalong/chapter05/game/game.java
Labels: chapter04, chapter05

#42 feat: 조건 분기 (6장)
  sunset0/src/main/java/com/cowaine/sunset0/Main.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter3/Money.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/README.md
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/if_overlap/Game.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/if_overlap/Magic.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/if_overlap/Member.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/rescope_replacemen/HotelRates.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/rescope_replacemen/Money.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/rescope_replacemen/PremiumRates.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/rescope_replacemen/RegularRates.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/magic/Fire.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/magic/Lightning.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/magic/Magic.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/policy/ExcellentCustomerPolicy.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/policy/ExcellentCustomerRule.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/policy/GoldCustomerPurchaseAmountRule.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/policy/PurchaseFrequencyRule.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/policy/PurchaseHistory.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/strategy_pattern/policy/ReturnRateRule.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/switch_overlap/Magic.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/switch_overlap/MagicInterface.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/switch_overlap/MagicManager.java
  sunset0/src/main/java/com/cowaine/sunset0/chapter6/switch_overlap/MagicType.java
Labels: chapter06

#46 [3rd Weeks] 6장 학습내용
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/BadIf.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/Flag.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/HotelRates.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/MagicManager.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/MagicType.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/MembershipManager.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/Money.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/PremiumRates.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/PurchaseHistory.java
  firewoody237/src/main/java/com/cowaine/firewoody237/bad_code/RegularRates.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/ExcellentCustomerPolicy.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/ExcellentCustomerRule.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Fire.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/GoldCustomerPolicy.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/GoldCustomerPurchaseAmountRule.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/GoodIf.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/HotelRates.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Magic.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/MagicManager.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Money.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/PurchaseFrequencyRule.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/RegularRates.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/ReturnRateRule.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/SeparateMethod.java
  firewoody237/src/main/java/com/cowaine/firewoody237/good_code/Water.java
  firewoody237/src/main/java/com/cowaine/firewoody237/studyMemo.md
Labels: chapter06

#49 Feature/coalong
  coalong/src/main/java/com/cowaine/coalong/chapter06/Circle.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/Fire.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/HealthCheck.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/HealthCondition.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/HellFire.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/Lightning.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/Magic.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/MagicManager.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/MagicMap.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/MagicType.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/Member.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/Rectangle.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/RpgGame.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/Shape.java
  coalong/src/main/java/com/cowaine/coalong/chapter06/ShapeInstance.java
Labels: chapter06

#51 Feature/corock
  corock/src/main/java/com/cowaine/corock/chapter06/Book.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/Customer.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/ExcellentCustomerPolicy.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/ExcellentCustomerRule.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/GoldCustomerPolicy.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/GoldCustomerPurchaseAmountRule.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/PurchaseFrequencyRule.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/PurchaseHistory.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/ReturnRateRule.java
  corock/src/main/java/com/cowaine/corock/chapter06/customer/SilverCustomerPolicy.java
  corock/src/main/java/com/cowaine/corock/chapter06/domain/Circle.java
  corock/src/main/java/com/cowaine/corock/chapter06/domain/Ellipse.java
  corock/src/main/java/com/cowaine/corock/chapter06/domain/Mall.java
  corock/src/main/java/com/cowaine/corock/chapter06/domain/Rectangle.java
  corock/src/main/java/com/cowaine/corock/chapter06/domain/Shape.java
  corock/src/main/java/com/cowaine/corock/chapter06/domain/Triangle.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/AttackManager.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/AttackPower.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/Damage.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/DamageType.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/Fire.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/HealthCondition.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/HellFire.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/HitPointDamage.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/Lightning.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/Magic.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/MagicAttackResponse.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/MagicManager.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/MagicPoint.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/MagicPointDamage.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/MagicType.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/Member.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/RpgService.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/Skill.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/StateType.java
  corock/src/main/java/com/cowaine/corock/chapter06/game/TechnicalPoint.java
  corock/src/main/java/com/cowaine/corock/chapter06/hotel/HotelRates.java
  corock/src/main/java/com/cowaine/corock/chapter06/hotel/Money.java
  corock/src/main/java/com/cowaine/corock/chapter06/hotel/PremiumRates.java
  corock/src/main/java/com/cowaine/corock/chapter06/hotel/RegularRates.java
Labels: chapter06

#52 Feature/snoopingh
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/Magic.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/MagicManager.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/MagicType.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/Member.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/lsp/HotelRates.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/lsp/Money.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/lsp/PremiumRates.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/lsp/RegularRates.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/strategy/Fire.java
  snoopingh/src/main/java/com/cowaine/snoopingh/chap06/strategy/Magic.java
Labels: chapter06

#55 Feature/irisation23
  irisation23/readme/irisation23-README.md
  irisation23/src/main/java/com/cowaine/sixth/domain/CustomerGradeManagement.java
  irisation23/src/main/java/com/cowaine/sixth/domain/ExcellentCustomerPolicy.java
  irisation23/src/main/java/com/cowaine/sixth/domain/ExcellentCustomerRule.java
  irisation23/src/main/java/com/cowaine/sixth/domain/Game.java
  irisation23/src/main/java/com/cowaine/sixth/domain/GoldCustomerPurchaseAmountRule.java
  irisation23/src/main/java/com/cowaine/sixth/domain/Magic.java
  irisation23/src/main/java/com/cowaine/sixth/domain/MagicElements.java
  irisation23/src/main/java/com/cowaine/sixth/domain/MagicManager.java
  irisation23/src/main/java/com/cowaine/sixth/domain/MagicType.java
  irisation23/src/main/java/com/cowaine/sixth/domain/Member.java
  irisation23/src/main/java/com/cowaine/sixth/domain/MemberState.java
  irisation23/src/main/java/com/cowaine/sixth/domain/PurchaseFrequencyRule.java
  irisation23/src/main/java/com/cowaine/sixth/domain/PurchaseHistory.java
  irisation23/src/main/java/com/cowaine/sixth/domain/ReturnRateRule.java
  irisation23/src/main/java/com/cowaine/sixth/domain/magic/Fire.java
  irisation23/src/main/java/com/cowaine/sixth/domain/magic/Lightning.java
  irisation23/src/main/java/com/cowaine/sixth/domain/magic/Magic.java
  irisation23/src/main/java/com/cowaine/sixth/one/NestedConditionalBranchesAndPoorReadability.java
  irisation23/src/main/java/com/cowaine/sixth/three/조건_분기_중복과_중첩.java
  irisation23/src/main/java/com/cowaine/sixth/two/NetstedSwitchOverlap.java
Labels: chapter06
